(()=>{'use strict';
const BOOK=window.TAMAKKUN_BOOK;if(!BOOK)return;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let unit='U1',query='',current=null,stage=0,startTs=0,activityState={};
const stages=['تشخيص','نشاط تفاعلي','تحقق','تثبيت'];
const allLessons=()=>BOOK.units.flatMap(u=>u.lessons);
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function progress(){try{return JSON.parse(localStorage.getItem('tamakkun_book_progress_'+(TamakkunAPI.getSession()?.user?.id||'guest'))||'{}')}catch{return {}}}
function saveProgress(p){localStorage.setItem('tamakkun_book_progress_'+(TamakkunAPI.getSession()?.user?.id||'guest'),JSON.stringify(p))}
async function event(type,extra={}){if(!current)return;try{await TamakkunAPI.request('record_learning_event',{lesson_code:current.code,event_type:type,interaction_type:extra.interaction_type||null,score:extra.score??null,duration_ms:Date.now()-startTs,payload:extra.payload||{}})}catch{}}
function renderTabs(){const h=$('#bookUnitTabs');if(!h)return;h.innerHTML=BOOK.units.map(u=>'<button data-u="'+u.id+'" class="'+(u.id===unit?'active':'')+'">'+esc(u.title)+'</button>').join('');h.querySelectorAll('button').forEach(b=>b.onclick=()=>{unit=b.dataset.u;renderTabs();renderCatalog()})}
function renderCatalog(){const host=$('#bookCatalog');if(!host)return;const p=progress(),u=BOOK.units.find(x=>x.id===unit);let rows=u.lessons.filter(l=>(l.title+' '+l.type+' '+l.goal).includes(query));host.innerHTML=rows.map(l=>'<article class="book-card"><div class="meta"><span class="type">'+esc(l.type)+'</span><span class="code">'+esc(l.code)+'</span></div><h4>'+esc(l.title)+'</h4><p>'+esc(l.goal)+'</p><footer><small>ص '+l.pages[0]+'–'+l.pages[1]+(p[l.code]?.mastered?' • متقن ✓':'')+'</small><button data-open="'+l.code+'">'+(p[l.code]?.mastered?'راجع الدرس':'ابدأ')+'</button></footer></article>').join('')||'<div class="empty-state">لا توجد نتائج.</div>';host.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openLesson(b.dataset.open));updateChip()}
function updateChip(){const p=progress(),all=allLessons();const done=all.filter(l=>p[l.code]?.mastered).length;const chip=$('#bookProgressChip');if(chip)chip.textContent=done+' / '+all.length+' متقن'}
function openLesson(code){current=allLessons().find(l=>l.code===code);if(!current)return;stage=0;startTs=Date.now();activityState={};$('#bookCatalog').hidden=true;$('#bookPlayer').hidden=false;renderPlayer();event('lesson_open',{payload:{content_version:BOOK.version}})}
function back(){event('lesson_close');current=null;$('#bookPlayer').hidden=true;$('#bookCatalog').hidden=false;renderCatalog()}
function renderPlayer(){const host=$('#bookPlayer');host.innerHTML='<article class="lesson-shell"><div class="lesson-top"><div><span class="eyebrow">'+esc(current.unit)+' • '+esc(current.type)+'</span><h3>'+esc(current.title)+'</h3><p>'+esc(current.goal)+'</p></div><div class="lesson-progress"><div class="lesson-progress-bar"><span style="width:'+((stage+1)/stages.length*100)+'%"></span></div><small>المرحلة '+(stage+1)+' من '+stages.length+'</small></div></div><div class="lesson-stage-nav">'+stages.map((x,i)=>'<span class="'+(i===stage?'active':'')+'">'+x+'</span>').join('')+'</div><div id="stageBody" class="lesson-stage"></div><div class="lesson-actions"><button class="secondary book-back" id="bookBack">العودة للكتاب</button></div></article>';$('#bookBack').onclick=back;renderStage()}
function renderStage(){if(stage===0)return renderQuestion(current.diag,'diagnostic');if(stage===1)return renderActivity();if(stage===2)return renderQuestion(current.mastery,'mastery');return renderFinish()}
function renderQuestion(q,kind){const [prompt,opts,answer,explain]=q;const h=$('#stageBody');h.innerHTML='<h4>'+(kind==='diagnostic'?'تشخيص سريع':'تحقق من الإتقان')+'</h4><p class="lead">'+esc(prompt)+'</p><div class="lesson-choices">'+opts.map((o,i)=>'<button data-i="'+i+'">'+esc(o)+'</button>').join('')+'</div><div id="lessonFb" class="lesson-feedback"></div>';h.querySelectorAll('[data-i]').forEach(b=>b.onclick=async()=>{const ok=+b.dataset.i===answer;h.querySelectorAll('[data-i]').forEach(x=>x.disabled=true);b.classList.add(ok?'good':'bad');const fb=$('#lessonFb');fb.classList.add('show');fb.innerHTML='<b>'+(ok?'إجابة صحيحة':'تحتاج محاولة تعلمية')+'</b><br>'+esc(explain);await event(kind==='diagnostic'?'diagnostic_answer':'mastery_answer',{score:ok?100:0,payload:{prompt,selected:+b.dataset.i,correct:answer}});setTimeout(()=>{if(kind==='diagnostic'){stage=1;renderPlayer()}else{activityState.mastery=ok;stage=3;renderPlayer()}},650)})}
function renderActivity(){const a=current.activity,h=$('#stageBody');h.innerHTML='<h4>نشاط تطبيقي</h4><p class="lead">'+esc(a.instruction)+'</p><div id="activityHost"></div><div id="lessonFb" class="lesson-feedback"></div>';if(a.kind==='classify')renderClassify(a);else if(a.kind==='sequence')renderSequence(a);else if(a.kind==='builder')renderBuilder(a);else if(a.kind==='trace')renderTrace(a);else if(a.kind==='record')renderRecord(a);else doneActivity()}
function doneActivity(score=100,payload={}){event('activity_complete',{interaction_type:current.activity.kind,score,payload});stage=2;setTimeout(()=>renderPlayer(),300)}
function renderClassify(a){const host=$('#activityHost');let items=[...a.items].sort(()=>Math.random()-.5),selected=null,answers={};host.innerHTML='<div class="sort-bank">'+items.map((x,i)=>'<button class="sort-item" data-item="'+i+'">'+esc(x[0])+'</button>').join('')+'</div><div class="classify-board">'+a.categories.map(c=>'<div class="classify-col" data-cat="'+esc(c)+'"><h5>'+esc(c)+'</h5><div></div></div>').join('')+'</div><div class="lesson-actions"><button class="primary" id="checkAct">تحقق</button></div>';host.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{selected=+b.dataset.item;host.querySelectorAll('[data-item]').forEach(x=>x.classList.toggle('selected',x===b))});host.querySelectorAll('[data-cat]').forEach(c=>c.onclick=()=>{if(selected===null)return;answers[selected]=c.dataset.cat;c.querySelector('div').appendChild(host.querySelector('[data-item="'+selected+'"]'));selected=null});$('#checkAct').onclick=()=>{const total=items.length,ok=items.reduce((n,x,i)=>n+(answers[i]===x[1]?1:0),0),score=Math.round(ok/total*100);const fb=$('#lessonFb');fb.classList.add('show');fb.textContent='نتيجتك في النشاط: '+score+'%';setTimeout(()=>doneActivity(score,{answers}),500)}}
function renderSequence(a){const host=$('#activityHost');let arr=[...a.items].sort(()=>Math.random()-.5);function draw(){host.innerHTML='<div class="sequence-list">'+arr.map((x,i)=>'<div class="sequence-row"><b>'+(i+1)+'</b><span>'+esc(x)+'</span><button data-up="'+i+'">↑</button><button data-down="'+i+'">↓</button></div>').join('')+'</div><div class="lesson-actions"><button class="primary" id="checkAct">تحقق</button></div>';host.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{let i=+b.dataset.up;if(i>0)[arr[i-1],arr[i]]=[arr[i],arr[i-1]];draw()});host.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>{let i=+b.dataset.down;if(i<arr.length-1)[arr[i+1],arr[i]]=[arr[i],arr[i+1]];draw()});$('#checkAct').onclick=()=>{const score=arr.filter((x,i)=>x===a.items[i]).length===arr.length?100:60;doneActivity(score,{order:arr})}}draw()}
function renderBuilder(a){const host=$('#activityHost');let built=[];host.innerHTML='<div class="sort-bank">'+a.tokens.map((x,i)=>'<button class="builder-token" data-t="'+i+'">'+esc(x)+'</button>').join('')+'</div><div class="builder-area" id="built"></div><div class="lesson-actions"><button class="primary" id="checkAct">تحقق</button><button class="secondary" id="resetAct">إعادة</button></div>';host.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{built.push(a.tokens[+b.dataset.t]);b.disabled=true;$('#built').textContent=built.join(' ← ')});$('#resetAct').onclick=()=>{built=[];renderBuilder(a)};$('#checkAct').onclick=()=>{const score=JSON.stringify(built)===JSON.stringify(a.target)?100:60;doneActivity(score,{built})}}
function renderTrace(a){$('#activityHost').innerHTML='<div class="trace-box">'+esc(a.sample)+'</div><div class="lesson-actions"><button class="primary" id="checkAct">أنهيت التدريب</button></div>';$('#checkAct').onclick=()=>doneActivity(100,{self_report:true})}
function renderRecord(a){const h=$('#activityHost');h.innerHTML='<div class="record-box"><button class="primary" id="recBtn">بدء التسجيل</button><p id="recStatus"></p><audio id="recAudio" controls hidden></audio></div>';let rec,chunks=[];$('#recBtn').onclick=async()=>{if(!rec){try{const s=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(s);rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{const blob=new Blob(chunks,{type:'audio/webm'}),url=URL.createObjectURL(blob),audio=$('#recAudio');audio.src=url;audio.hidden=false;$('#recStatus').textContent='استمع لتسجيلك ثم أكمل.';$('#recBtn').textContent='إتمام النشاط';$('#recBtn').onclick=()=>doneActivity(100,{recorded:true});s.getTracks().forEach(t=>t.stop())};rec.start();$('#recStatus').textContent='جارٍ التسجيل...';$('#recBtn').textContent='إيقاف التسجيل';$('#recBtn').onclick=()=>rec.stop()}catch{$('#recStatus').textContent='تعذر استخدام الميكروفون. يمكنك إكمال النشاط بعد التدريب بصوت مرتفع.';setTimeout(()=>doneActivity(80,{recorded:false}),1200)}}}}
function renderFinish(){const ok=!!activityState.mastery,h=$('#stageBody'),p=progress();h.innerHTML='<div class="lesson-result '+(ok?'':'support')+'"><h4>'+(ok?'أتقنت الفكرة الأساسية ✓':'نحتاج تثبيتًا قصيرًا قبل الإتقان')+'</h4><p>'+(ok?esc(current.challenge):esc(current.support[0]+' '+current.support[1]))+'</p><div class="reflection-box"><textarea id="reflection" placeholder="اكتب بجملة واحدة: ما الذي فهمته الآن؟"></textarea></div><div class="lesson-actions"><button class="primary" id="finishLesson">'+(ok?'حفظ الإتقان':'حفظ التقدم والعودة')+'</button></div></div>';$('#finishLesson').onclick=async()=>{p[current.code]={mastered:ok,updatedAt:new Date().toISOString(),reflection:$('#reflection').value};saveProgress(p);await event(ok?'lesson_mastered':'lesson_support_needed',{score:ok?100:60,payload:{reflection:$('#reflection').value}});try{await TamakkunAPI.saveProgress({lesson_code:current.code,score:ok?100:60,knowledge_percent:ok?90:70,application_percent:ok?90:65,reasoning_percent:ok?85:55,status:ok?'mastered':'needs_support',kwl_l:$('#reflection').value})}catch{}back();updateChip()}}
$('#bookSearch')?.addEventListener('input',e=>{query=e.target.value.trim();renderCatalog()});
renderTabs();renderCatalog();
window.TamakkunBook={openLesson};
})();