-- مخطط أولي مستقل لمنصة اللغة العربية
-- ينفذ لاحقًا في مشروع Supabase جديد بعد ربط الحساب الصحيح.

create table if not exists profiles (
  id uuid primary key,
  role text not null check (role in ('teacher','student','admin')),
  full_name text not null,
  grade text,
  class_name text,
  created_at timestamptz default now()
);

create table if not exists units (
  id bigint generated by default as identity primary key,
  title text not null,
  semester text not null,
  sort_order int not null default 0,
  is_published boolean default false
);

create table if not exists lessons (
  id bigint generated by default as identity primary key,
  unit_id bigint references units(id) on delete cascade,
  title text not null,
  lesson_type text not null,
  summary text,
  estimated_minutes int default 10,
  mastery_threshold int default 80,
  sort_order int not null default 0,
  is_published boolean default false
);

create table if not exists lesson_objectives (
  id bigint generated by default as identity primary key,
  lesson_id bigint references lessons(id) on delete cascade,
  objective text not null,
  sort_order int not null default 0
);

create table if not exists lesson_points (
  id bigint generated by default as identity primary key,
  lesson_id bigint references lessons(id) on delete cascade,
  title text not null,
  short_explanation text not null,
  example_text text,
  sort_order int not null default 0
);

create table if not exists lesson_videos (
  id bigint generated by default as identity primary key,
  lesson_id bigint references lessons(id) on delete cascade,
  lesson_point_id bigint references lesson_points(id) on delete set null,
  video_url text not null,
  title text,
  duration_seconds int
);

create table if not exists questions (
  id bigint generated by default as identity primary key,
  lesson_id bigint references lessons(id) on delete cascade,
  lesson_point_id bigint references lesson_points(id) on delete set null,
  level text check (level in ('knowledge','application','reasoning')),
  stem text not null,
  options jsonb not null,
  correct_answer text not null,
  explanation text,
  is_mastery_question boolean default false
);

create table if not exists lesson_attempts (
  id bigint generated by default as identity primary key,
  student_id uuid references profiles(id) on delete cascade,
  lesson_id bigint references lessons(id) on delete cascade,
  started_at timestamptz default now(),
  completed_at timestamptz,
  score numeric,
  mastery_status text check (mastery_status in ('in_progress','mastered','needs_support'))
);

create table if not exists question_attempts (
  id bigint generated by default as identity primary key,
  lesson_attempt_id bigint references lesson_attempts(id) on delete cascade,
  question_id bigint references questions(id) on delete cascade,
  selected_answer text,
  is_correct boolean,
  answered_at timestamptz default now()
);

create table if not exists student_point_mastery (
  student_id uuid references profiles(id) on delete cascade,
  lesson_point_id bigint references lesson_points(id) on delete cascade,
  mastery_percent numeric default 0,
  last_attempt_at timestamptz,
  primary key(student_id, lesson_point_id)
);


-- ملف الإنجاز: يحتفظ بالأصل والتأمل وحالة العرض للمعلم.
create table if not exists student_portfolio_items (
  id bigint generated by default as identity primary key,
  student_id uuid references profiles(id) on delete cascade,
  lesson_id bigint references lessons(id) on delete set null,
  title text not null,
  category text not null,
  reflection text,
  storage_path text not null,
  teacher_note text,
  is_featured boolean default false,
  created_at timestamptz default now(),
  reviewed_at timestamptz
);

-- تفضيلات تعلم حالية تساعد على تنويع العرض، ولا تمثل نمطًا ثابتًا أو قدرة.
create table if not exists student_learning_preferences (
  student_id uuid primary key references profiles(id) on delete cascade,
  responses jsonb not null default '{}'::jsonb,
  visual_score int not null default 0,
  verbal_score int not null default 0,
  active_score int not null default 0,
  primary_preference text check (primary_preference in ('visual','verbal','active')),
  updated_at timestamptz default now()
);

-- لقطة تشخيصية محدثة لمستوى الطالب في المادة.
create table if not exists student_subject_progress (
  student_id uuid primary key references profiles(id) on delete cascade,
  overall_percent numeric default 0,
  knowledge_percent numeric default 0,
  application_percent numeric default 0,
  reasoning_percent numeric default 0,
  mastered_lessons int default 0,
  assessed_lessons int default 0,
  current_level text check (current_level in ('needs_support','developing','mastered','advanced')),
  strongest_dimension text,
  priority_dimension text,
  updated_at timestamptz default now()
);
