-- مخطط أولي مستقل لمنصة اللغة العربية
-- ينفذ لاحقًا في مشروع Supabase جديد بعد ربط الحساب الصحيح.

create table if not exists profiles (
  id uuid primary key,
  role text not null check (role in ('teacher','student','admin')),
  full_name text not null,
  grade text,
  class_name text,
  created_at timestamptz default now()
);

create table if not exists units (
  id bigint generated by default as identity primary key,
  title text not null,
  semester text not null,
  sort_order int not null default 0,
  is_published boolean default false
);

create table if not exists lessons (
  id bigint generated by default as identity primary key,
  unit_id bigint references units(id) on delete cascade,
  title text not null,
  lesson_type text not null,
  summary text,
  estimated_minutes int default 10,
  mastery_threshold int default 80,
  sort_order int not null default 0,
  is_published boolean default false
);

create table if not exists lesson_objectives (
  id bigint generated by default as identity primary key,
  lesson_id bigint references lessons(id) on delete cascade,
  objective text not null,
  sort_order int not null default 0
);

create table if not exists lesson_points (
  id bigint generated by default as identity primary key,
  lesson_id bigint references lessons(id) on delete cascade,
  title text not null,
  short_explanation text not null,
  example_text text,
  sort_order int not null default 0
);

create table if not exists lesson_videos (
  id bigint generated by default as identity primary key,
  lesson_id bigint references lessons(id) on delete cascade,
  lesson_point_id bigint references lesson_points(id) on delete set null,
  video_url text not null,
  title text,
  duration_seconds int
);

create table if not exists questions (
  id bigint generated by default as identity primary key,
  lesson_id bigint references lessons(id) on delete cascade,
  lesson_point_id bigint references lesson_points(id) on delete set null,
  level text check (level in ('knowledge','application','reasoning')),
  stem text not null,
  options jsonb not null,
  correct_answer text not null,
  explanation text,
  is_mastery_question boolean default false
);

create table if not exists lesson_attempts (
  id bigint generated by default as identity primary key,
  student_id uuid references profiles(id) on delete cascade,
  lesson_id bigint references lessons(id) on delete cascade,
  started_at timestamptz default now(),
  completed_at timestamptz,
  score numeric,
  mastery_status text check (mastery_status in ('in_progress','mastered','needs_support'))
);

create table if not exists question_attempts (
  id bigint generated by default as identity primary key,
  lesson_attempt_id bigint references lesson_attempts(id) on delete cascade,
  question_id bigint references questions(id) on delete cascade,
  selected_answer text,
  is_correct boolean,
  answered_at timestamptz default now()
);

create table if not exists student_point_mastery (
  student_id uuid references profiles(id) on delete cascade,
  lesson_point_id bigint references lesson_points(id) on delete cascade,
  mastery_percent numeric default 0,
  last_attempt_at timestamptz,
  primary key(student_id, lesson_point_id)
);
