alter table public.lessons add column if not exists source_start_page integer;
alter table public.lessons add column if not exists source_end_page integer;
alter table public.lessons add column if not exists content_version text;

create table if not exists public.learning_events (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.app_accounts(id) on delete cascade,
  lesson_id uuid not null references public.lessons(id) on delete cascade,
  event_type text not null,
  interaction_type text,
  score integer,
  duration_ms integer,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.learning_events enable row level security;
create index if not exists idx_learning_events_student_lesson on public.learning_events(student_id,lesson_id,created_at desc);
create index if not exists idx_learning_events_type on public.learning_events(event_type,created_at desc);

-- The production migration also imports the textbook lesson catalog (U1-00..U1-15, U2-00..U2-15).
-- Canonical interactive content lives in book-course-data.js; lesson metadata is mirrored in public.lessons.
